using GoogleApi.Attributes;

namespace GoogleApi.Places.Types
{
  public enum Languages
  {
    [Code("ar")] Arabic,
    [Code("kn")] Kannada,
    [Code("bg")] Bulgarian,
    [Code("ko")] Korean,
    [Code("bn")] Bengali,
    [Code("lt")] Lithuanian,
    [Code("ca")] Catalan,
    [Code("lv")] Latvian,
    [Code("cs")] Czech,
    [Code("ml")] Malayalam,
    [Code("da")] Danish,
    [Code("mr")] Marathi,
    [Code("de")] German,
    [Code("nl")] Dutch,
    [Code("el")] Greek,
    [Code("no")] Norwegian,
    [Code("en")] English,
    [Code("pl")] Polish,
    [Code("en-AU")] EnglishAustralian,
    [Code("pt")] Portuguese,
    [Code("en-GB")] EnglishGreatBritain,
    [Code("pt-BR")] PortugueseBrazil,
    [Code("es")] Spanish,
    [Code("pt-PT")] PortuguesePortugal,
    [Code("eu")] Basque,
    [Code("ro")] Romanian,
    [Code("ru")] Russian,
    [Code("fa")] Farsi,
    [Code("sk")] Slovak,
    [Code("fi")] Finnish,
    [Code("sl")] Slovenian,
    [Code("fil")] Filipino,
    [Code("sr")] Serbian,
    [Code("fr")] French,
    [Code("sv")] Swedish,
    [Code("gl")] Galician,
    [Code("ta")] Tamil,
    [Code("gu")] Gujarati,
    [Code("te")] Telugu,
    [Code("hi")] Hindi,
    [Code("th")] Thai,
    [Code("hr")] Croatian,
    [Code("tl")] Tagalog,
    [Code("hu")] Hungarian,
    [Code("tr")] Turkish,
    [Code("id")] Indonesian,
    [Code("uk")] Ukrainian,
    [Code("it")] Italian,
    [Code("vi")] Vietnamese,
    [Code("iw")] Hebrew,
    [Code("zh-CN")] ChineseSimplified,
    [Code("ja")] Japanese,
    [Code("zh-TW")] ChineseTraditional
  }
}